import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '../globals.css'
import {NextAuthProvider} from "@/app/session-provider";


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Bug Tracker - Login',
    description: 'Generated by create next app',
}


export default function RootLayout({children,}: {
    children: React.ReactNode
}) {

    return (

        <html lang="en">
        <body className={inter.className}>
        <NextAuthProvider>
            <>
                {children}
                {/*<div className="container-fluid">*/}
                {/*    {children}*/}
                {/*</div>*/}
            </>
        </NextAuthProvider>
        </body>
        </html>

    )
}
